mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('people.urls')),
]

mysite/people/urls.py
from django.conf.urls import url 

from . import views

app_name = "people"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^list/$', views.list, name='list')
]

mysite/people/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Person(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(unique=True)

mysite/people/forms.py
from django.forms import ModelForm
from .models import Person

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['name', 'email']

mysite/people/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from .models import Person
from .forms import PersonForm

def index(request):
    return render(request, 'people/welcome.html', {'welcome_message': 'welcome to the people inventory'})

def add(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/list')
        else:
            return render(request, 'people/add.html', {'form': form})
    else:
        return render(request, 'people/add.html')

def list(request):
    people = Person.objects.all()
    print people
    return render(request, 'people/list.html', {'people':people})

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block page_title %}{% endblock page_title %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
{% block page %}{% endblock page %}
</div>
</body>
</html>

mysite/templates/people/add.html
{% extends 'base.html' %}

{% block page_title %}Add Person{% endblock page_title%}

{% block page %}
    <div class="col-xs-4 col-md-offset-3">
        <h2>Add a Person</h2>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form action="{% url 'people:add' %}" method="post" style="width: 500px">
        {% csrf_token %}
            {{form.name.errors}}
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                <input type="text" class="form-control custom-input" name="name" placeholder="Full Name">
            </div>
            <br>

            {{form.email.errors}}
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-email"></i></span>
                <input type="email" class="form-control custom-input" name="email" placeholder="Enter Email">
            </div>
            <br>
            <button type="submit" class="center-block btn btn-default">Submit</button>
        </form>
    </div>
{% endblock page %}

mysite/templates/people/list.html
{% extends 'base.html' %}

{% block page_title %}People List{% endblock page_title%}

{% block page %}
<div class="container">
  <h2>People List</h2>
  <ul class="list-group">
  {% for person in people %}
    <li class="list-group-item">
        <div class="row">
            <div class="col-xs-6"><strong>{{person.name}}</strong></div>
            <div class="col-xs-6"><i>{{person.email}}</i></div>
        </div>
    </li>
  {% endfor %}
  </ul>
</div>
{% endblock page %}

mysite/templates/people/welcome.html
{% extends 'base.html' %}

{% block page_title %}Welcome{% endblock page_title%}

{% block page %}
    <div><h2>{{welcome_message}}</h2></div>
    <div>
        <p>add people <a href="{% url 'people:add' %}">here</a></p>
        <p>view people <a href="{% url 'people:list' %}">here</a></p>
    </div>
{% endblock page %}